### ISSUE TITLE
Error invoking callback 

### ISSUE THREAD

**Issue by iclassdon** [NockyCZ/CS2-Deathmatch#24]
18:35:38 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Deathmatch.DeathmatchCore.ParseVector(String pos) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Functions\Spawns.cs:line 405
   at Deathmatch.DeathmatchCore.PerformRespawn(CCSPlayerController player, Int32 team, Boolean IsBot) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Functions\Spawns.cs:line 41
   at Deathmatch.DeathmatchCore.<>c__DisplayClass53_0.<OnPlayerDeath>b__0() in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Events.cs:line 104
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass7_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 105
L 03/01/2024 - 18:35:40: "Sas<6><BOT><CT>" [-1223 654 0] killed "Bank<4><BOT><TERRORIST>" [-1432 1113 1] with "ump45"
18:35:42 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Deathmatch.DeathmatchCore.ParseVector(String pos) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Functions\Spawns.cs:line 405
   at Deathmatch.DeathmatchCore.PerformRespawn(CCSPlayerController player, Int32 team, Boolean IsBot) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Functions\Spawns.cs:line 41
   at Deathmatch.DeathmatchCore.<>c__DisplayClass53_0.<OnPlayerDeath>b__0() in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Events.cs:line 104
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass7_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 105

**Comment by NockyCZ** [comment]
Can you send me your config ?

**Comment by NockyCZ** [comment]
Fixed - https://github.com/NockyCZ/CS2-Deathmatch/releases/tag/v1.0.9
