### ISSUE TITLE
(cssharp:Core) Error invoking callback

### ISSUE THREAD

**Issue by luizfranzon** [NockyCZ/CS2-Deathmatch#28]
Hey!
I followed the instructions to install the plugin, but when i try to connect to the  localhost server, i got this error
I don't know if I'm doing something wrong :P

- Windows 11
- CounterStrikeSharp v197
- mmsource2.0.0

And I'm using the WindowsGSM to start the server

```
10:51:23 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.UInt16.ToString()
   at Deathmatch.DeathmatchCore.OnWeaponCanAcquire(DynamicHook hook) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Events.cs:line 204
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120
10:51:23 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.UInt16.ToString()
   at Deathmatch.DeathmatchCore.OnWeaponCanAcquire(DynamicHook hook) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Events.cs:line 204
   at InvokeStub_Func`2.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 120
```

**Comment by weeestar** [comment]
I heard that It doesn't work on Windows. I've used Docker in order to have my DM server working.

**Comment by luizfranzon** [comment]
> I heard that It doesn't work on Windows. I've used Docker in order to have my DM server working.

I did the same thing and it worked. This information should probably be in the project's README lol

**Comment by weeestar** [comment]
I guess so :)
