### ISSUE TITLE
[ERROR] (cssharp:Core) Error invoking callback [Plugins: Deathmatch]

### ISSUE THREAD

**Issue by Kfalt** [NockyCZ/CS2-Deathmatch#35]
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.UInt16.ToString()
   at Deathmatch.Deathmatch.OnWeaponCanAcquire(DynamicHook hook) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Events.cs:line 210
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
  
===== End of inner exception stack trace =====
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100


2024-04-28 00:38:23.798 +02:00 [**ERROR**] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 
---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.UInt16.ToString()
   at Deathmatch.Deathmatch.OnWeaponCanAcquire(DynamicHook hook) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Events.cs:line 210
   at InvokeStub_Func`2.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   
===== End of inner exception stack trace =====
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionRefere
nce.cs:line 100 ```

**Comment by NockyCZ** [comment]
The plugin is only for Linux servers

**Comment by Kfalt** [comment]
Is it possible for you to fix this problem because it really annoys me to run the server on a Linux VM on my dedicated server at home

**Comment by Kfalt** [comment]
otherwise what version of debian should I install so that your plugin works correctly and gets the best possible performance from it ?

**Comment by NockyCZ** [comment]
> Is it possible for you to fix this problem because it really annoys me to run the server on a Linux VM on my dedicated server at home

Maybe in the future I'll look at it, I don't plan to yet

> otherwise what version of debian should I install so that your plugin works correctly and gets the best possible performance from it ?

Idk, probably the latest version

**Comment by weeestar** [comment]
I run a Debian 11 and its working perfectly
