### ISSUE TITLE
[EROR] (cssharp:Core) Error invoking callback ( FunctionReference.cs:line 100 )

### ISSUE THREAD

**Issue by Kfalt** [NockyCZ/CS2-Deathmatch#37]
```
**14:34:22 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Deathmatch.Deathmatch.OnTakeDamage(DynamicHook hook) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Events.cs:line 190
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
  
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100**
```

![image](https://github.com/NockyCZ/CS2-Deathmatch/assets/168311137/b203ec08-2032-44cd-ad62-72f9a82a01c3)

**Comment by gabrielsdelima75** [comment]
metamod 1290
css 228
[#4:LOADED]: "Deathmatch Core" (1.1.2) by Nocky
**same problem**

**Comment by asdfxD** [comment]
Same

meta 1290
css 228
Only Deathmatch

The error log is ~200 Mb after 3 hours.

**Comment by NockyCZ** [comment]
I will look at it

**Comment by NockyCZ** [comment]
Fixed - https://github.com/NockyCZ/CS2-Deathmatch/releases/tag/v1.1.3
