### ISSUE TITLE
 [EROR] (cssharp:Core) Error invoking callback

### ISSUE THREAD

**Issue by tamirKashy** [NockyCZ/CS2-Deathmatch#39]
CS2 Server error + a lag maker:

22:51:11 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Deathmatch.Deathmatch.OnTakeDamage(DynamicHook hook) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Events.cs:line 190
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by NockyCZ** [comment]
Already fixed - https://github.com/NockyCZ/CS2-Deathmatch/issues/37
