### ISSUE TITLE
cs2 update today - new plugin error

### ISSUE THREAD

**Issue by y3request** [NockyCZ/CS2-Deathmatch#42]
Valve pushed update. Updated server, changed nothing.

> 03:52:01 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1090
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionVoid`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionVoid.cs:line 100
   at CounterStrikeSharp.API.Core.CBasePlayerController.SetPawn(CBasePlayerPawn pawn) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CBasePlayerController.cs:line 19
   at CounterStrikeSharp.API.Core.CCSPlayerController.Respawn() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs:line 139
   at Deathmatch.Deathmatch.PerformRespawn(CCSPlayerController player, CsTeam team, Boolean IsBot) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Functions\Spawns.cs:line 55
   at Deathmatch.Deathmatch.<>c__DisplayClass55_0.<OnPlayerDeath>b__0() in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Events.cs:line 107
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

**Comment by y3request** [comment]
Server appears to be working fine despite the error. So no rush, no worries.
Just keeping you posted.

**Comment by asdfxD** [comment]
What OS? No error here @Linux.

CSS 242 & DM 1.1.6

**Comment by y3request** [comment]
> What OS? No error here @Linux.
> 
> CSS 242 & DM 1.1.6

Ah, I just woke up and update my server. It is because I have not updated the plugin. 
Did not realize NockyCZ was so fast, my bad.
