### ISSUE TITLE
Error after CS2 Update today

### ISSUE THREAD

**Issue by y3request** [NockyCZ/CS2-Deathmatch#52]
I have not updated anything other than the server so sorry if there is already a fix. 
Here is the error I am getting...

> 05:25:51 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1090
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionVoid`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionVoid.cs:line 100
   at CounterStrikeSharp.API.Core.CBasePlayerController.SetPawn(CBasePlayerPawn pawn) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CBasePlayerController.cs:line 19
   at CounterStrikeSharp.API.Core.CCSPlayerController.Respawn() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs:line 139
   at Deathmatch.Deathmatch.PerformRespawn(CCSPlayerController player, CsTeam team, Boolean IsBot) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Deathmatch\Functions\Spawns.cs:line 54
   at Deathmatch.Deathmatch.<>c__DisplayClass73_0.<OnPlayerDeath>b__0() in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Deathmatch\Events.cs:line 130
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

Also will add every thing appears to be working, despite the error.

**Comment by NockyCZ** [comment]
Use latest CSS version, you need to update gamedata

**Comment by y3request** [comment]
You're right it fixed. Thanks.
