### ISSUE TITLE
Error after last CS2 update

### ISSUE THREAD

**Issue by vitordarela** [NockyCZ/CS2-Deathmatch#57]
Hello,
After updating cs2, these errors started to occur in the logs. I have already updated the latest version of CSSHARP but I still have these errors.

```
[EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1090
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.InvokeInternalVoid(Object[] args) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 77
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.MemoryFunctionVoid`4.Invoke(T1 arg1, T2 arg2, T3 arg3, T4 arg4) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/MemoryFunctionVoid.cs:line 100
   at CounterStrikeSharp.API.Core.CBasePlayerController.SetPawn(CBasePlayerPawn pawn) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CBasePlayerController.cs:line 19
   at CounterStrikeSharp.API.Core.CCSPlayerController.Respawn() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Model/CCSPlayerController.cs:line 139
   at Deathmatch.Deathmatch.PerformRespawn(CCSPlayerController player, CsTeam team, Boolean IsBot) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Deathmatch\Functions\Spawns.cs:line 38
   at Deathmatch.Deathmatch.<>c__DisplayClass73_0.<OnPlayerDeath>b__0() in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Deathmatch\Events.cs:line 130
   at InvokeStub_Action.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100
```

The error seems here `player.Respawn();`

**Comment by NockyCZ** [comment]
You need to update gamedata : https://github.com/roflmuffin/CounterStrikeSharp/pull/547/commits/03288715f3f33500f83c7bbe817c8bbcb0f09d49

You can update it manually or wait until the CSS update comes out

**Comment by vitordarela** [comment]
Sounds perfect! I updated manually and worked, thank you mate!
