### ISSUE TITLE
[ERROR] After last CS2 Update error started

### ISSUE THREAD

**Issue by vitordarela** [NockyCZ/CS2-Deathmatch#64]
```
23:48:13 [INFO] (cssharp:PluginContext) Loading plugin Ranks_Tag
23:48:13 [INFO] (cssharp:PluginContext) Finished loading plugin [Ranks] Tag
23:48:13 [INFO] (cssharp:PluginContext) Loading plugin Deathmatch
23:48:13 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/steam/cs2-dedicated/game/csgo/addons/counterstrikesharp/plugins/Deathmatch/Deathmatch.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
   at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1077
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.Hook(Func`2 handler, HookMode mode) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 62
   at Deathmatch.Deathmatch.Load(Boolean hotReload) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Deathmatch\Deathmatch.cs:line 39
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

```

And also 

```
[Deathmatch] Spawns list is empty, you got something wrong!
[Deathmatch] Spawns list is empty, you got something wrong!
[Deathmatch] Spawns list is empty, you got something wrong!
[Deathmatch] Spawns list is empty, you got something wrong!
[Deathmatch] Spawns list is empty, you got something wrong!
[Deathmatch] Spawns list is empty, you got something wrong!
```

**Comment by vitordarela** [comment]
Solution: You need to update `Deathmatch.json` (gamedata)

```
"CCSPlayer_CanAcquire": {
    "signatures": {
      "library": "server",
      "windows": "\\x48\\x8B\\xC4\\x44\\x89\\x40\\x18\\x48\\x89\\x48\\x08\\x55\\x56",
      "linux": "\\x55\\x48\\x89\\xE5\\x41\\x57\\x41\\x56\\x41\\x55\\x49\\x89\\xCD\\x41\\x54\\x53\\x48\\x83\\xEC"
    }
  }
```
