### ISSUE TITLE
unable to run plugin

### ISSUE THREAD

**Issue by Soramagic7** [NockyCZ/CS2-Deathmatch#65]
2024-10-22 19:56:48.183 +08:00 [INFO] (cssharp:PluginContext) Loading plugin Deathmatch
2024-10-22 19:56:48.234 +08:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/cs2/game/csgo/addons/counterstrikesharp/plugins/Deathmatch/Deathmatch.dll
System.MissingFieldException: Field not found: 'CounterStrikeSharp.API.Modules.Memory.VirtualFunctions.CCSPlayer_ItemServices_CanAcquireFunc'.
   at Deathmatch.Deathmatch.Load(Boolean hotReload)
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

how to fix it

**Comment by NockyCZ** [comment]
Use latest css version

**Comment by ccsimplyspolit** [comment]
![{D07C66FA-2AE3-40A5-BC5B-97F3A4A09BCB}](https://github.com/user-attachments/assets/897f8d73-ef3b-4d86-9a81-c0f8bbd3e1af)

**Comment by NockyCZ** [comment]
Im not talking about the deathmatch plugin version, but about the css

**Comment by Soramagic7** [comment]
it is broken again after today's game update= =

**Comment by NockyCZ** [comment]
You have to wait for the css update or update it yourself - https://github.com/roflmuffin/CounterStrikeSharp/pull/641

**Comment by Soramagic7** [comment]
its fine, thank you!
