### ISSUE TITLE
Infinity loading plugin

### ISSUE THREAD

**Issue by ccsimplyspolit** [NockyCZ/CS2-Deathmatch#66]
meta list
```
Listing 1 plugin:
  [01] CounterStrikeSharp (v284 @ 5c9d38b) by Roflmuffin
```
css_plugins list
```
  List of all plugins currently loaded by CounterStrikeSharp: 1 plugins loaded.
  [#1:LOADING]: "Deathmatch Core" (1.2.2) by Nocky
```

meta version
```
 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1314
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Oct  3 2024 15:12:54
    Built from: https://github.com/alliedmodders/metamod-source/commit/557121c
    Build ID: 1314:557121c
    http://www.metamodsource.net/
```

FULL LOG of cssharp:
[log-cssharp20241025.txt](https://github.com/user-attachments/files/17517037/log-cssharp20241025.txt)
[log-all20241025.txt](https://github.com/user-attachments/files/17517038/log-all20241025.txt)

**Comment by ccsimplyspolit** [comment]
```

2024-10-25 09:21:46.923 +03:00 [INFO] (cssharp:PluginContext) Loading plugin Deathmatch
2024-10-25 09:21:46.985 +03:00 [EROR] (cssharp:PluginManager) Failed to load plugin from /game/game/csgo/addons/counterstrikesharp/plugins/Deathmatch/Deathmatch.dll
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
   at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1087
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.Hook(Func`2 handler, HookMode mode) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 62
   at Deathmatch.Deathmatch.Load(Boolean hotReload) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Deathmatch\Deathmatch.cs:line 32
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93

```

**Comment by ccsimplyspolit** [comment]
![image](https://github.com/user-attachments/assets/d90e298c-900a-4283-99c5-d60754c43aa0)

Fixed w this
