### ISSUE TITLE
CCSPlayer_ItemServices_CanAcquire broken again?

### ISSUE THREAD

**Issue by ccsimplyspolit** [NockyCZ/CS2-Deathmatch#67]
```
CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.ScriptContext.CheckErrors() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/ScriptContext.cs:line 187
   at CounterStrikeSharp.API.Core.NativeAPI.HookFunction(IntPtr function, InputArgument hook, Boolean post) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1087
   at CounterStrikeSharp.API.Modules.Memory.DynamicFunctions.BaseMemoryFunction.Hook(Func`2 handler, HookMode mode) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/DynamicFunctions/BaseMemoryFunction.cs:line 62
   at Deathmatch.Deathmatch.Load(Boolean hotReload) in C:\Users\Mates-PC\Desktop\SourceFactory\Projects\CSharp\Deathmatch\Deathmatch\Deathmatch.cs:line 32
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
2024-11-20 11:20:47.392 +03:00 [EROR] (cssharp:PluginManager) OnAllPluginsLoaded failed
```

**Comment by ccsimplyspolit** [comment]
looks like fix

`[CCSPlayer_ItemServices_CanAcquire]
linux - 55 48 89 E5 41 57 41 56 48 8D 45 ? 41 55 41 54 53 48 89 CB 48 83 EC`
