### ISSUE TITLE
[EROR] (cssharp:Core) Error invoking callback

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [NockyCZ/CS2-Deathmatch#7]
00:05:34 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.ReadInt64(IntPtr ptr, Int32 ofs)
   at System.Runtime.InteropServices.Marshal.ReadIntPtr(IntPtr ptr)
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetPointer[T](IntPtr pointer, String className, String memberName) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 116
   at CounterStrikeSharp.API.Core.CBasePlayerPawn.get_WeaponServices() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:line 5183
   at Deathmatch.DeathmatchCore.IsHaveWeaponFromSlot(CCSPlayerController player, Int32 slot) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Functions.cs:line 238
   at Deathmatch.DeathmatchCore.SetupPlayerWeapons(CCSPlayerController player, Boolean bNewMode) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Functions.cs:line 501
   at Deathmatch.DeathmatchCore.OnPlayerSpawn(EventPlayerSpawn event, GameEventInfo info) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Events.cs:line 39
   at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 71

**Comment by NockyCZ** [comment]
Fixed - https://github.com/NockyCZ/CS2-Deathmatch/releases/tag/v1.2.1

**Comment by BrutalCSEjziponken** [comment]
Ty! :)

The other errors I closed were user error. :P
