### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [NockyCZ/CS2-Deathmatch#9]
00:21:21 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/Deathmatch/Deathmatch.dll
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Deathmatch.Configuration.CreateOrLoadCustomModes(String filepath) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Configs.cs:line 124
   at Deathmatch.DeathmatchCore.Load(Boolean hotReload) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Deathmatch.cs:line 99
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 201
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 52
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 34

**Comment by BrutalCSEjziponken** [comment]
Hm. So This morning this problem was gone. But now when I restarted the server its there again. With the latest hotfix.

[Info] - Trampoline - Bounds of relative addresses accessed [0xffffffffffffffff, (nil)]
[Info] - Trampoline - Attempting to allocate trampoline within +-2GB range of 0x7f75eee08c00
[Info] - Trampoline - Allocated trampoline at 0x7f766ee07000 (using 1 attempts)
10:31:31 [EROR] (cssharp:PluginManager) Failed to load plugin from /home/container/game/csgo/addons/counterstrikesharp/plugins/Deathmatch/Deathmatch.dll
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: String. Path '', line 1, position 3.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Deathmatch.Configuration.CreateOrLoadCustomModes(String filepath) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Configs.cs:line 124
   at Deathmatch.DeathmatchCore.Load(Boolean hotReload) in C:\Users\Mates-PC\Desktop\WASD\Deathmatch\Deathmatch.cs:line 99
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 201
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 52
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 34

**Comment by BrutalCSEjziponken** [comment]
User error. Closed.
